stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
            script: |
              sudo apt update
              sudo apt install openjdk-8-jdk
              sudo apt install git
              sudo apt install maven
              sudo apt install pcregrep
              sudo apt-get install zlib1g-dev
              sudo apt-get install libssl-dev